import { normalizeName } from "@/utils/normalizeNames";

const OFFICIAL_CHAPTER_NAMES = [
    "Absolvers",
    "Accipiters",
    "Adamantine Lions",
    "Adulators",
    "Angel Guard",
    "Angels Encarmine",
    "Angels Eradicant",
    "Angels Erythrean",
    "Angels Excelsis",
    "Angels Glorious",
    "Angels Numinous",
    "Angels of Absolution",
    "Angels of Damnation",
    "Angels of Defiance",
    "Angels of Fire",
    "Angels of Fury",
    "Angels of Iron",
    "Angels of Light",
    "Angels of Penance",
    "Angels of Purgatory",
    "Angels of Redemption",
    "Angels of Repentance",
    "Angels of Retribution",
    "Angels of the Grail",
    "Angels of Vengeance",
    "Angels of Vigilance",
    "Angels of Wrath",
    "Angels Penitent",
    "Angels Porphyr",
    "Angels Puissant",
    "Angels Redeemed",
    "Angels Repentant",
    "Angels Resplendent",
    "Angels Revenant",
    "Angels Sanguine",
    "Angels Vermillion",
    "Angels Vindicant",
    "Aquiloan Brotherhood",
    "Astral Bears",
    "Astral Blades",
    "Astral Drakes",
    "Astral Fists",
    "Astral Hawks",
    "Astral Knights",
    "Astral Spears",
    "Atlantian Spears",
    "Auric Patricians",
    "Aurora Chapter",
    "Aurora Talons",
    "Avengers",
    "Avenging Sons",
    "Benedictors",
    "Black Consuls",
    "Black Crusaders",
    "Black Dragons",
    "Black Guard",
    "Black Inculpators",
    "Black Ravens",
    "Black Talons",
    "Black Templars",
    "Black Vipers",
    "Black Vultures",
    "Black Wings",
    "Blades of Vengeance",
    "Blazoned Legion",
    "Blood Angels",
    "Blood Dragons",
    "Blood Drinkers",
    "Blood Eagles",
    "Blood Knights",
    "Blood Legion",
    "Blood Ravens",
    "Blood Scythes",
    "Blood Swords",
    "Blood Tigers",
    "Blood Wings",
    "Bone Knives",
    "Brazen Claws",
    "Brazen Consuls",
    "Brazen Fists",
    "Brazen Minotaurs",
    "Brazen Skulls",
    "Bringers of Judgement",
    "Brotherhood of a Thousand",
    "Brothers of Jarad",
    "Brothers of the Red",
    "Brothers Penitent",
    "Burning Blood",
    "Carcharodons",
    "Carmine Blades",
    "Castellans of the Rift",
    "Celebrants",
    "Celestial Guard",
    "Celestial Lions",
    "Celestial Swords",
    "Celestian Guard",
    "Cerulean Guard",
    "Champions of Thanatos",
    "Charnel Guard",
    "Chorus of Eltain",
    "Clerics of Steel",
    "Condemnors",
    "Consecrators",
    "Contenders",
    "Covenant of Fire",
    "Cowled Wardens",
    "Crimson Castellans",
    "Crimson Consuls",
    "Crimson Fists",
    "Crimson Guard",
    "Crimson Knights",
    "Crimson Legion",
    "Crimson Paladins",
    "Crimson Raptors",
    "Crimson Sabres",
    "Crimson Scions",
    "Crimson Scythes",
    "Crimson Shades",
    "Crimson Swords",
    "Crimson Talons",
    "Crimson Templars",
    "Cruor Blades",
    "Crusaders",
    "Crusaders of Dorn",
    "Dark Angels",
    "Dark Brotherhood",
    "Dark Crusaders",
    "Dark Eagles",
    "Dark Hands",
    "Dark Hunters",
    "Dark Krakens",
    "Dark Paladins",
    "Dark Sons",
    "Dark Swords",
    "Dark Templars",
    "Darkspires",
    "Death Eagles",
    "Death Hawks",
    "Death Hunters",
    "Death Knights",
    "Death Spectres",
    "Death Strike",
    "Death Wardens",
    "Deathwatch",
    "Desert Lions",
    "Destroyers",
    "Dictators",
    "Disciples of Blood",
    "Disciples of Caliban",
    "Doom Eagles",
    "Doom Griffons",
    "Doom Legion",
    "Doom Warriors",
    "Doomsayers",
    "Dragon Lords",
    "Dragonspears",
    "Eagle Warriors",
    "Ebon Knights",
    "Emperor's Claws",
    "Emperor's Hands",
    "Emperor's Hawks",
    "Emperor's Scythes",
    "Emperor's Shadows",
    "Emperor's Shields",
    "Emperor's Spears",
    "Emperor's Storm",
    "Emperor's Swords",
    "Emperor's Warbringers",
    "Emperor's Wolves",
    "Emperor's Wrath",
    "Espandors",
    "Excoriators",
    "Excubants",
    "Execrators",
    "Executioners",
    "Exemplars",
    "Exorcists",
    "Exsanguinators",
    "Falling Star",
    "Farstalkers",
    "Fire Angels",
    "Fire Claws",
    "Fire Hawks",
    "Fire Lords",
    "Firebreathers",
    "Fists Exemplar",
    "Flame Eagles",
    "Flame Falcons",
    "Flesh Eaters",
    "Flesh Tearers",
    "Fulminators",
    "Genesis Chapter",
    "Golden Blades",
    "Golden Gryphons",
    "Golden Halos",
    "Golden Paladins",
    "Golden Sons",
    "Gore Golems",
    "Gorgons",
    "Graven Fists",
    "Graven Spectres",
    "Grey Giants",
    "Grey Knights",
    "Grey Slayers",
    "Grief Bringers",
    "Griffon Lords",
    "Guardians of Celeres",
    "Guardians of the Covenant",
    "Halo Brethren",
    "Halo Dragons",
    "Hammers of Dhrex",
    "Hammers of Dorn",
    "Hammers of Retribution",
    "Harbingers",
    "Hawk Lords",
    "Helion Legion",
    "Heralds of Ultramar",
    "Heralds of Vengeance",
    "Honoured Sons",
    "Hospitallers",
    "Hounds of Demos",
    "Howling Griffons",
    "Illustrians",
    "Immortal Hearts",
    "Imperial Castellans",
    "Imperial Fists",
    "Imperial Harbingers",
    "Imperial Hawks",
    "Imperial Paladins",
    "Imperial Ravagers",
    "Imperial Stars",
    "Imperial Talons",
    "Imperius Reavers",
    "Inceptors",
    "Inculcators",
    "Interceptors",
    "Invaders",
    "Invictors",
    "Inviolators",
    "Iron Champions",
    "Iron Crusaders",
    "Iron Drakes",
    "Iron Fists",
    "Iron Hands",
    "Iron Hawks",
    "Iron Hearts",
    "Iron Hounds",
    "Iron Knights",
    "Iron Lords",
    "Iron Ravens",
    "Iron Scepters",
    "Iron Shield",
    "Iron Snakes",
    "Iron Talons",
    "Jade Scorpions",
    "Justicars",
    "Knights Cerulean",
    "Knights Excelsior",
    "Knights of Abhorrence",
    "Knights of Byzantium",
    "Knights of Dorn",
    "Knights of Eternity",
    "Knights of Gryphonne",
    "Knights of the Chalice",
    "Knights of the Crimson Order",
    "Knights of the Flame",
    "Knights of the Raven",
    "Knights of Thunder",
    "Knights Sanguine",
    "Knights Unyielding",
    "Lamenters",
    "Lances of Pteros",
    "Lectors of Ixis",
    "Legion of Night",
    "Legion of the Damned",
    "Libators",
    "Liberators",
    "Lion Warriors",
    "Lionguard",
    "Lions Azure",
    "Lions Defiant",
    "Lions Sable",
    "Lords of Wrath",
    "Malevolent",
    "Mantis Warriors",
    "Marauders",
    "Marines August",
    "Marines Errant",
    "Marines Errantor",
    "Marines Exemplar",
    "Marines Malevolent",
    "Marines Mordant",
    "Marines Vigilant",
    "Marines Vindicant",
    "Masters of Protelus",
    "Mentors",
    "Metamarines",
    "Minotaurs",
    "Mortifactors",
    "Necropolis Hawks",
    "Nemesis",
    "Nemesors",
    "Night Hawks",
    "Night Sentinels",
    "Night Swords",
    "Night Watch",
    "Nova Legion",
    "Nova Wings",
    "Novamarines",
    "Oblators",
    "Obsidian Glaives",
    "Obsidian Jaguars",
    "Omega Marines",
    "Pain Bringers",
    "Panthers",
    "Patriarchs of Ulixis",
    "Penitent Blades",
    "Penitents",
    "Persecutors of Darkness",
    "Praetors of Orpheus",
    "Praetors of Ultramar",
    "Prime Absolvers",
    "Prophets of Mercury",
    "Purgators",
    "Purple Stars",
    "Rainbow Warriors",
    "Rampagers",
    "Raptors",
    "Raven Covenant",
    "Raven Guard",
    "Raven's Watch",
    "Reborn",
    "Reclaimers",
    "Red Consuls",
    "Red Dragons",
    "Red Hunters",
    "Red Knights",
    "Red Legion",
    "Red Scimitars",
    "Red Scorpions",
    "Red Seraphs",
    "Red Talons",
    "Red Templars",
    "Red Wings",
    "Red Wolves",
    "Redeemed",
    "Redeemers",
    "Regents of Gheren",
    "Reparators",
    "Retractors",
    "Retributors",
    "Revilers",
    "Rhetors",
    "Rift Cobras",
    "Rift Stalkers",
    "Ruby Crescents",
    "Sable Brotherhood",
    "Sable Knights",
    "Sable Swords",
    "Salamanders",
    "Sanguine Host",
    "Scar Lords",
    "Scions of Iron",
    "Scions of Sanguinius",
    "Scythes of the Emperor",
    "Selenarchs",
    "Shadow Falcons",
    "Shadow Griffons",
    "Shadow Haunters",
    "Shadow Hawks",
    "Shadow Wolves",
    "Shadowhawks",
    "Silver Drakes",
    "Silver Eagles",
    "Silver Guard",
    "Silver Phoenixes",
    "Silver Sabres",
    "Silver Skulls",
    "Silver Stars",
    "Silver Templars",
    "Skull Bearers",
    "Sky Sentinels",
    "Solar Hawks",
    "Sons of Antaeus",
    "Sons of Dorn",
    "Sons of Galathor",
    "Sons of Gorgax",
    "Sons of Guilliman",
    "Sons of Helios",
    "Sons of Jaghatai",
    "Sons of Medusa",
    "Sons of Orar",
    "Sons of Orpheus",
    "Sons of Sanguinius",
    "Sons of the Kraken",
    "Sons of the Phoenix",
    "Sons of the Raven",
    "Space Sharks",
    "Space Wolves",
    "Star Dragons",
    "Star Leopards",
    "Star Phantoms",
    "Star Scorpions",
    "Steel Confessors",
    "Stone Gauntlets",
    "Stone Hearts",
    "Storm Callers",
    "Storm Falcons",
    "Storm Giants",
    "Storm Hawks",
    "Storm Lords",
    "Storm Ravens",
    "Storm Reapers",
    "Storm Wardens",
    "Storm Warriors",
    "Storm Wings",
    "Stormwalkers",
    "Stormwatchers",
    "Subjugators",
    "Supplicators",
    "Swords of Praesium",
    "Swords of the Emperor",
    "Tarantulas",
    "Taurans",
    "Tempest Guard",
    "Tempestors",
    "Templars of Blood",
    "Templars of the Covenant",
    "Terror Tigers",
    "The Nameless",
    "The Remnants",
    "The Unnamed",
    "Tiger Claws",
    "Tigers Argent",
    "Tome Keepers",
    "Tormented",
    "Tormentors",
    "Tributors",
    "Ultramarines",
    "Umbral Knights",
    "Umbral Titans",
    "Valedictors",
    "Valiant Blades",
    "Venerators",
    "Venerators of Osiron",
    "Verydian Hawks",
    "Victors",
    "Vindicators",
    "Viper Legion",
    "Void Axes",
    "Void Daggers",
    "Void Tridents",
    "Vorpal Swords",
    "War Bearers",
    "Wardens of the Philae",
    "Warhawks",
    "Warmongers",
    "Warrior Adepts",
    "Warriors Tempest",
    "Watchguards",
    "White Consuls",
    "White Minotaurs",
    "White Panthers",
    "White Scars",
    "White Sentinels",
    "White Templars",
    "Widowmakers",
    "Wolfspear",
    "Yellow Jackets"
];

export const OFFICIAL_CHAPTER_BLACKLIST = new Set(
    OFFICIAL_CHAPTER_NAMES.map(normalizeName)
);