// import { normalizeName } from "@/utils/normalizeNames";

// const officialNames = [
//     "Order of the Ardent Oath",
//     "Order of the Ashen Mantle",
//     "Order of the August Vigil",
//     "Order of the Azure Sky",
//     "Order of the Baroque Chalice",
//     "Order of the Black Banner",
//     "Order of the Black Sepulchre",
//     "Order of the Blazing Horizon",
//     "Order of the Blessed Enquiry",
//     "Order of the Blessed Laurel",
//     "Order of the Bloody Chalice",
//     "Order of the Bloody Rose",
//     "Order of the Bleeding Heart",
//     "Order of the Blue Robe",
//     "Order of Blooming Darkness",
//     "Order of the Cardinal Mistress",
//     "Order of the Cleansing Water",
//     "Order of the Crimson Oath",
//     "Order of the Crimson Sepulchre",
//     "Order of the Crimson Tear",
//     "Order of the Dawn",
//     "Order of the Dire Moon",
//     "Order of the Divine Fire",
//     "Order of the Divine Lamentation",
//     "Order Dolphinus",
//     "Order of the Ebon Chalice",
//     "Order of the Ember Thorn",
//     "Order of the Eternal Bloom",
//     "Order of the Eternal Candle",
//     "Order of the Eternal Flame",
//     "Order of the Eternal Gate",
//     "Order of the Eternal Sands",
//     "Order of the Ermine Mantle",
//     "Order of the Fiery Tear",
//     "Order of the Gate",
//     "Order of the Glowing Chalice",
//     "Order of the Golden Light",
//     "Order of the Golden Lioness",
//     "Order of the Holy Flame",
//     "Order of the Holy Seal",
//     "Order of the Holy Word",
//     "Order of the Iron Rose",
//     "Order of the Key",
//     "Order of the Lambent Chorus",
//     "Order of the Lexicon",
//     "Order of the Martyred Heart",
//     "Order of the Maudlin Countenance",
//     "Order of the Midnight Vigil",
//     "Order of the Motive Force",
//     "Order of the Night Angels",
//     "Order of the Omnissian Cog",
//     "Order of Our Hunting Mistress",
//     "Order of Our Martyred Lady",
//     "Order of the Quill",
//     "Order of the Rising Phoenix",
//     "Order of Rosaria",
//     "Order of the Sacred Coin",
//     "Order of the Sacred Oath",
//     "Order of the Sacred Pinion",
//     "Order of the Sacred Rose",
//     "Order of the Sanctified Blood",
//     "Order of the Scarlet Rose",
//     "Order of Serenity",
//     "Order of the Silver Hand",
//     "Order of the Silver Lily",
//     "Order of the Silver Shroud",
//     "Order of the Sisters of the Promethean Flame",
//     "Order of the Sublime Adoration",
//     "Order of the Torch",
//     "Order of the Valorous Heart",
//     "Order of the Virgin Rose",
//     "Order of the White Rose",
//     "Order of the Wounded Heart",
//     "Daughters of Guilliman",
// ];

// export const blacklist = new Set(officialNames.map(normalizeName)
// );