import { normalizeName } from "@/utils/normalizeNames";

const OFFICIAL_CHAOS_WARBAND_NAMES = [
    "Emperor's Children",
    "Iron Warriors",
    "Night Lords",
    "World Eaters",
    "Death Guard",
    "Thousand Sons",
    "Black Legion",
    "Word Bearers",
    "Alpha Legion",
    "Angron's Fury",
    "Anointed",
    "Apocalypse Company",
    "Apostles of Contagion",
    "Apostles of MinthRas",
    "Argent Hammers",
    "Astral Blades",
    "Astral Claws",
    "Athkor's Destroyers",
    "Avenging Sons",
    "Baleful Eye",
    "Beasts of Annihilation",
    "Berserkers of Kharadon",
    "Berserkers of Skallathrax",
    "Betrayers of Pain",
    "Bilious Ones",
    "Bitter Sons",
    "Black Brethren of Ayreas",
    "Black Feast",
    "The Black Psalm",
    "Black Skull",
    "Blades Eternal",
    "The Blades of Magnus",
    "Blades of Rage",
    "Blades of the Despoiler",
    "Bleak Brotherhood",
    "Bleeding Eye",
    "Blood Storm",
    "Bloody Path",
    "The Blighted Claw",
    "Blood Disciples",
    "Blood Gorgons",
    "Blood Legion of Khorne",
    "Blood Wolves",
    "Bloodborn",
    "Bloodlords",
    "Brazen Drakes",
    "Brazen Guard",
    "Bringers of Decay",
    "Bronze Gorgons",
    "Brotherhood of Blood",
    "Brotherhood of Darkness",
    "Brotherhood of Dust",
    "Brotherhood of Lethe",
    "Brotherhood of the Plague",
    "Brotherhood of Unclean Mercy",
    "Brothers of Darkness",
    "Brothers of Livos",
    "Brothers of Retaliation",
    "Brothers of the Anvil",
    "The Broken",
    "Butcherhorde",
    "Carrion Hounds",
    "Children of Blain",
    "Children of Purgatos",
    "Children of Torment",
    "The Chosen of Heiros",
    "Chosen of Nemeroth",
    "Claws of Lorek",
    "The Cleaved",
    "Clerics of Steel",
    "Company of Misery",
    "Company of the Shadow",
    "Corpsemakers",
    "Corpus Brethren",
    "Coven of Nine",
    "Creations of Bile",
    "Crimson Sabres",
    "Crimson Slaughter",
    "Crimson Sons",
    "Crusaders of Dorn",
    "The Crystal Harbingers",
    "Crystal Wyverns",
    "Cursed Company",
    "Damned Company of Lord Caustos",
    "Dark Castellans",
    "Dark Tusks",
    "Death Falcons",
    "Death Mongers",
    "Death Shadows",
    "Disciples of Destruction",
    "Dolorous Gnaw",
    "Dolorous Guard",
    "Dragon Warriors",
    "Eagles Iridescent",
    "Ebon Sentinels",
    "Emissaries of Wasting Death",
    "Emperor's Wolves 8th Company",
    "Empyrion's Blight",
    "Eightscarred",
    "Encrusted Blade",
    "Endless Murder",
    "Exquisite Host",
    "Extinction Angels",
    "The Faithless",
    "Favoured Sons",
    "Fecund Ones",
    "Filth-favoured",
    "Fire Reavers",
    "Fists of Brass",
    "Fists of Olchis",
    "Flame Falcons",
    "The Flawless Host",
    "Flickering Blades",
    "The Flylords",
    "Foresworn",
    "Forgeborn",
    "The Fractured",
    "Germinatoris",
    "Gladiator Group 138",
    "Glooming Lords",
    "Gorehands",
    "Gorehounds",
    "Goremongers",
    "Grand Order of Hermetic Blades",
    "Graven Fists",
    "Graven Spectres",
    "Grey Death",
    "Grey Slayers",
    "Hakanor's Reavers",
    "The Harvest",
    "Harvest Macabre",
    "The Hedonistarii",
    "Heralds of Despair",
    "Honourless",
    "Hounds of Abaddon",
    "Iconoclasts",
    "Illustrians",
    "Invictors",
    "Invocators",
    "Iron Drakes",
    "Justicars",
    "Killmongers",
    "Kindled Spirits",
    "Knights Excelsior",
    "Knights of Blood",
    "Lances of Pteros",
    "Lectors of Ixis",
    "Lionguard",
    "Lifeslayers",
    "Lords of Decay",
    "Lords of Desolation",
    "Lords of Pain",
    "Lords of Silence",
    "Lord Skchalick's Elite",
    "Magma Hounds",
    "Malefactors",
    "Mind-Eaters",
    "Metal Claw",
    "Mouldering Claw",
    "Murderghosts",
    "Night Reapers",
    "Night Stalkers",
    "Nightkillers",
    "Nightwing",
    "The Oath-Broken",
    "Oblivion Butchers",
    "Oracles of Change",
    "Pallid Hand",
    "Poisoned Chalice",
    "Predator Legion",
    "The Prism of Fate",
    "Prodigal Sons",
    "Prophets of the Blighted Path",
    "Prophets of the Seven",
    "Punishers",
    "The Purge",
    "Putrid Choir",
    "The Pyre",
    "Ravagers",
    "The Reborn",
    "Red Corsairs",
    "Red Echo",
    "Red Heralds",
    "The Reflected Ones",
    "Relictors",
    "The Revelation of Gore",
    "Rotworm Brotherhood",
    "Rusted Claws",
    "The Sanctified",
    "Sanctors of Terra",
    "Sanguine Sons",
    "Savage Swords",
    "Screaming Skulls",
    "The Scourged",
    "The Sectai Prosperine",
    "Seekers of Truth",
    "Sensorians",
    "Sentinels",
    "Serpents of Light",
    "The Shadowed Ones",
    "Shatter Corps",
    "Shattered Tower",
    "Shining Blades",
    "The Shriven",
    "Shrouded Hand",
    "Sigilites",
    "Silver Guards",
    "Silver Sons",
    "Six-Cursed",
    "Skull Takers of Hans Kho'ren",
    "Skulltakers",
    "Skyrar's Dark Wolves",
    "Slaughterkin",
    "Smogrot Brotherhood",
    "Sons of the Cyclops",
    "Sons of Damnation",
    "Sons of Gideon",
    "Sons of Hate",
    "Sons of Malice",
    "Sons of Midnight",
    "Sons of Slaughter",
    "Sons of Sorrow",
    "Sons of the Maggot",
    "Sons of Ulthunas",
    "Sons of Vengeance",
    "Sons of the Eye",
    "Soul Drinkers",
    "Spears of Olympus",
    "Star Gryphons",
    "Steel Brethren",
    "Steel Cobras",
    "Steel Heart",
    "Suppurant Sting",
    "Swords of Khargoth",
    "Swords of Epiphany",
    "The Tainted",
    "Tainted Lung",
    "Tainted Sons",
    "Talons of Anathrax",
    "Tempest Legion",
    "Ten Thousand Eyes",
    "Tenebrae",
    "Terror Lords",
    "Thralls of Magnus",
    "Thunder Barons",
    "Tiger Claws",
    "The Tizcan Host",
    "The Tormented",
    "True Sons",
    "Twisted Blades",
    "The Unhallowed",
    "Vectors of Pox",
    "Vengeance Chapter",
    "Venom Thorns",
    "Violators",
    "Voidrippers",
    "Viridian Consuls",
    "Warband of Sektoth",
    "Warp Gheists",
    "Warp Ghosts",
    "Warriors of Aggannor",
    "Warriors of Mayhem",
    "Weeping Legion",
    "Wolf Brothers",
    "Wolves of Horus",
    "The Wrath",
    "Wrathful Dead"
];


export const OFFICIAL_CHAOS_WARBAND_BLACKLIST = new Set(
    OFFICIAL_CHAOS_WARBAND_NAMES.map(normalizeName)
);
