export const colorList = [

    // Base Paints
    { name: "White Scar", hex: "#FFFFFF", type: "Base", brand: "Citadel" },
    { name: "Abaddon Black", hex: "#0f0f0f", type: "Base", brand: "Citadel" },
    { name: "Averlund Sunset", hex: "#F0B947", type: "Base", brand: "Citadel" },
    { name: "Barak-Nar Burgundy", hex: "#411F37", type: "Base", brand: "Citadel" },
    { name: "Bugman's Glow", hex: "#774F46", type: "Base", brand: "Citadel" },
    { name: "Caledor Sky", hex: "#436493", type: "Base", brand: "Citadel" },
    { name: "Caliban Green", hex: "#1C3E1F", type: "Base", brand: "Citadel" },
    { name: "Castellan Green", hex: "#314721", type: "Base", brand: "Citadel" },
    { name: "Catachan Flesh", hex: "#422F2A", type: "Base", brand: "Citadel" },
    { name: "Celestra Grey", hex: "#8EA0A1", type: "Base", brand: "Citadel" },
    { name: "Corvus Black", hex: "#1C191A", type: "Base", brand: "Citadel" },
    { name: "Daemonette Hide", hex: "#635F7D", type: "Base", brand: "Citadel" },
    { name: "Death Guard Green", hex: "#6E7552", type: "Base", brand: "Citadel" },
    { name: "Death Korps Drab", hex: "#40463C", type: "Base", brand: "Citadel" },
    { name: "Deathworld Forest", hex: "#586134", type: "Base", brand: "Citadel" },
    { name: "Dryad Bark", hex: "#2E2E29", type: "Base", brand: "Citadel" },
    { name: "Gal Vorback Red", hex: "#47283D", type: "Base", brand: "Citadel" },
    { name: "Grey Seer", hex: "#A1A3A5", type: "Base", brand: "Citadel" },
    { name: "Hobgrot Hide", hex: "#9A813D", type: "Base", brand: "Citadel" },
    { name: "Incubi Darkness", hex: "#1A3034", type: "Base", brand: "Citadel" },
    { name: "Ionrach Skin", hex: "#97A185", type: "Base", brand: "Citadel" },
    { name: "Jokaero Orange", hex: "#D94A2E", type: "Base", brand: "Citadel" },
    { name: "Kantor Blue", hex: "#0E194C", type: "Base", brand: "Citadel" },
    { name: "Khorne Red", hex: "#5C1510", type: "Base", brand: "Citadel" },
    { name: "Lupercal Green", hex: "#152F2E", type: "Base", brand: "Citadel" },
    { name: "Macragge Blue", hex: "#223E76", type: "Base", brand: "Citadel" },
    { name: "Mechanicus Standard Grey", hex: "#3E494A", type: "Base", brand: "Citadel" },
    { name: "Mephiston Red", hex: "#88241C", type: "Base", brand: "Citadel" },
    { name: "Morghast Bone", hex: "#BAA878", type: "Base", brand: "Citadel" },
    { name: "Mournfang Brown", hex: "#441A12", type: "Base", brand: "Citadel" },
    { name: "Naggaroth Night", hex: "#3B2F4E", type: "Base", brand: "Citadel" },
    { name: "Night Lords Blue", hex: "#152E59", type: "Base", brand: "Citadel" },
    { name: "Orruk Flesh", hex: "#96BF7D", type: "Base", brand: "Citadel" },
    { name: "Nocturne Green", hex: "#202D2C", type: "Base", brand: "Citadel" },
    { name: "Phoenician Purple", hex: "#3F0E4F", type: "Base", brand: "Citadel" },
    { name: "Rakarth Flesh", hex: "#9A978C", type: "Base", brand: "Citadel" },
    { name: "Ratskin Flesh", hex: "#9D684E", type: "Base", brand: "Citadel" },
    { name: "Rhinox Hide", hex: "#443333", type: "Base", brand: "Citadel" },
    { name: "Screamer Pink", hex: "#6F2044", type: "Base", brand: "Citadel" },
    { name: "Steel Legion Drab", hex: "#564F34", type: "Base", brand: "Citadel" },
    { name: "Stegadon Scale Green", hex: "#22455B", type: "Base", brand: "Citadel" },
    { name: "The Fang", hex: "#475A6E", type: "Base", brand: "Citadel" },
    { name: "Thondia Brown", hex: "#50342F", type: "Base", brand: "Citadel" },
    { name: "Thousand Sons Blue", hex: "#244F6B", type: "Base", brand: "Citadel" },
    { name: "Waaagh! Flesh", hex: "#203C38", type: "Base", brand: "Citadel" },
    { name: "Wraithbone", hex: "#D8D0B3", type: "Base", brand: "Citadel" },
    { name: "XV-88", hex: "#664A22", type: "Base", brand: "Citadel" },
    { name: "Zandri Dust", hex: "#948D5D", type: "Base", brand: "Citadel" },

    // Layer Paints
    { name: "Administratum Grey", hex: "#979A93", type: "Layer", brand: "Citadel" },
    { name: "Ahriman Blue", hex: "#326D86", type: "Layer", brand: "Citadel" },
    { name: "Alaitoc Blue", hex: "#394F80", type: "Layer", brand: "Citadel" },
    { name: "Altdorf Guard Blue", hex: "#35468F", type: "Layer", brand: "Citadel" },
    { name: "Baharroth Blue", hex: "#6FB9C6", type: "Layer", brand: "Citadel" },
    { name: "Balor Brown", hex: "#7E5623", type: "Layer", brand: "Citadel" },
    { name: "Baneblade Brown", hex: "#8A7B6A", type: "Layer", brand: "Citadel" },
    { name: "Bestigor Flesh", hex: "#C48A5B", type: "Layer", brand: "Citadel" },
    { name: "Bloodreaver Flesh", hex: "#644A4A", type: "Layer", brand: "Citadel" },
    { name: "Blue Horror", hex: "#A0B2CA", type: "Layer", brand: "Citadel" },
    { name: "Cadian Fleshtone", hex: "#B77859", type: "Layer", brand: "Citadel" },
    { name: "Calgar Blue", hex: "#34497A", type: "Layer", brand: "Citadel" },
    { name: "Dark Reaper", hex: "#3C4D4C", type: "Layer", brand: "Citadel" },
    { name: "Dawnstone", hex: "#696F68", type: "Layer", brand: "Citadel" },
    { name: "Deathclaw Brown", hex: "#A36654", type: "Layer", brand: "Citadel" },
    { name: "Dechala Lilac", hex: "#AE97C4", type: "Layer", brand: "Citadel" },
    { name: "Deepkin Flesh", hex: "#AAB59F", type: "Layer", brand: "Citadel" },
    { name: "Doombull Brown", hex: "#501210", type: "Layer", brand: "Citadel" },
    { name: "Dorn Yellow", hex: "#FDF573", type: "Layer", brand: "Citadel" },
    { name: "Elysian Green", hex: "#718944", type: "Layer", brand: "Citadel" },
    { name: "Emperor's Children", hex: "#A74971", type: "Layer", brand: "Citadel" },
    { name: "Eshin Grey", hex: "#494C4E", type: "Layer", brand: "Citadel" },
    { name: "Evil Sunz Scarlet", hex: "#AE2F25", type: "Layer", brand: "Citadel" },
    { name: "Fenrisian Grey", hex: "#7491AE", type: "Layer", brand: "Citadel" },
    { name: "Fire Dragon Bright", hex: "#E48B5A", type: "Layer", brand: "Citadel" },
    { name: "Flash Gitz Yellow", hex: "#FCF351", type: "Layer", brand: "Citadel" },
    { name: "Fulgrim Pink", hex: "#E7ACC7", type: "Layer", brand: "Citadel" },
    { name: "Gauss Blaster Green", hex: "#8CBDA5", type: "Layer", brand: "Citadel" },
    { name: "Genestealer Purple", hex: "#70599E", type: "Layer", brand: "Citadel" },
    { name: "Kabalite Green", hex: "#3D8564", type: "Layer", brand: "Citadel" },
    { name: "Karak Stone", hex: "#AF9363", type: "Layer", brand: "Citadel" },
    { name: "Loren Forest", hex: "#506A32", type: "Layer", brand: "Citadel" },
    { name: "Lothern Blue", hex: "#5097C6", type: "Layer", brand: "Citadel" },
    { name: "Moot Green", hex: "#5FAB52", type: "Layer", brand: "Citadel" },
    { name: "Pink Horror", hex: "#813256", type: "Layer", brand: "Citadel" },
    { name: "Russ Grey", hex: "#576E81", type: "Layer", brand: "Citadel" },
    { name: "Screaming Skull", hex: "#B8BE9B", type: "Layer", brand: "Citadel" },
    { name: "Temple Guard Blue", hex: "#4A9087", type: "Layer", brand: "Citadel" },
    { name: "Troll Slayer Orange", hex: "#DF733B", type: "Layer", brand: "Citadel" },
    { name: "Ulthuan Grey", hex: "#C7DBD4", type: "Layer", brand: "Citadel" },
    { name: "Warpfiend Grey", hex: "#65646C", type: "Layer", brand: "Citadel" },

    // Metallics
    { name: "Grey Knight's Steel", hex: "#a5b4be", type: "Metallic", brand: "Citadel" },
    { name: "Iron Hand's Steel", hex: "#a99d95", type: "Metallic", brand: "Citadel" },
    { name: "Iron Warriors", hex: "#63605d", type: "Metallic", brand: "Citadel" },
    { name: "Leadbelcher", hex: "#8a8a8a", type: "Metallic", brand: "Citadel" },
    { name: "Retributor Armour", hex: "#ebb854", type: "Metallic", brand: "Citadel" },
    { name: "Runelord Brass", hex: "#74624d", type: "Metallic", brand: "Citadel" },
    { name: "Screaming Bell", hex: "#cc7d51", type: "Metallic", brand: "Citadel" },
    { name: "Warplock Bronze", hex: "#aa6243", type: "Metallic", brand: "Citadel" },
    { name: "Balthasar Gold", hex: "#9b684b", type: "Metallic", brand: "Citadel" }
];