export const colorList = [
    { name: "Abaddon Black", hex: "#000000" },
    { name: "Averlund Sunset", hex: "#F0B947" },
    { name: "Barak-Nar Burgundy", hex: "#411F37" },
    { name: "Bugman's Glow", hex: "#774F46" },
    { name: "Caledor Sky", hex: "#436493" },
    { name: "Caliban Green", hex: "#1C3E1F" },
    { name: "Castellan Green", hex: "#314721" },
    { name: "Catachan Flesh", hex: "#422F2A" },
    { name: "Celestra Grey", hex: "#8EA0A1" },
    { name: "Corvus Black", hex: "#1C191A" },
    { name: "Daemonette Hide", hex: "#635F7D" },
    { name: "Death Guard Green", hex: "#6E7552" },
    { name: "Death Korps Drab", hex: "#40463C" },
    { name: "Deathworld Forest", hex: "#586134" },
    { name: "Dryad Bark", hex: "#2E2E29" },
    { name: "Gal Vorback Red", hex: "#47283D" },
    { name: "Grey Seer", hex: "#A1A3A5" },
    { name: "Hobgrot Hide", hex: "#9A813D" },
    { name: "Incubi Darkness", hex: "#1A3034" },
    { name: "Ionrach Skin", hex: "#97A185" },
    { name: "Jokaero Orange", hex: "#D94A2E" },
    { name: "Kantor Blue", hex: "#0E194C" },
    { name: "Khorne Red", hex: "#5C1510" },
    { name: "Lupercal Green", hex: "#152F2E" },
    { name: "Macragge Blue", hex: "#223E76" },
    { name: "Mechanicus Standard Grey", hex: "#3E494A" },
    { name: "Mephiston Red", hex: "#88241C" },
    { name: "Morghast Bone", hex: "#BAA878" },
    { name: "Mournfang Brown", hex: "#441A12" },
    { name: "Naggaroth Night", hex: "#3B2F4E" },
    { name: "Night Lords Blue", hex: "#152E59" },
    { name: "Orruk Flesh", hex: "#96BF7D" },
    { name: "Nocturne Green", hex: "#202D2C" },
    { name: "Phoenician Purple", hex: "#3F0E4F" },
    { name: "Rakarth Flesh", hex: "#9A978C" },
    { name: "Ratskin Flesh", hex: "#9D684E" },
    { name: "Rhinox Hide", hex: "#443333" },
    { name: "Screamer Pink", hex: "#6F2044" },
    { name: "Steel Legion Drab", hex: "#564F34" },
    { name: "Stegadon Scale Green", hex: "#22455B" },
    { name: "The Fang", hex: "#475A6E" },
    { name: "Thondia Brown", hex: "#50342F" },
    { name: "Thousand Sons Blue", hex: "#244F6B" },
    { name: "Waaagh! Flesh", hex: "#203C38" },
    { name: "Wraithbone", hex: "#D8D0B3" },
    { name: "XV-88", hex: "#664A22" },
    { name: "Zandri Dust", hex: "#948D5D" },
    { name: "Administratum Grey", hex: "#979A93" },
    { name: "Ahriman Blue", hex: "#326D86" },
    { name: "Alaitoc Blue", hex: "#394F80" },
    { name: "Altdorf Guard Blue", hex: "#35468F" },
    { name: "Baharroth Blue", hex: "#6FB9C6" },
    { name: "Balor Brown", hex: "#7E5623" },
    { name: "Baneblade Brown", hex: "#8A7B6A" },
    { name: "Bestigor Flesh", hex: "#C48A5B" },
    { name: "Bloodreaver Flesh", hex: "#644A4A" },
    { name: "Blue Horror", hex: "#A0B2CA" },
    { name: "Cadian Fleshtone", hex: "#B77859" },
    { name: "Calgar Blue", hex: "#34497A" },
    { name: "Dark Reaper", hex: "#3C4D4C" },
    { name: "Dawnstone", hex: "#696F68" },
    { name: "Deathclaw Brown", hex: "#A36654" },
    { name: "Dechala Lilac", hex: "#AE97C4" },
    { name: "Deepkin Flesh", hex: "#AAB59F" },
    { name: "Doombull Brown", hex: "#501210" },
    { name: "Dorn Yellow", hex: "#FDF573" },
    { name: "Elysian Green", hex: "#718944" },
    { name: "Emperor's Children", hex: "#A74971" },
    { name: "Eshin Grey", hex: "#494C4E" },
    { name: "Evil Sunz Scarlet", hex: "#AE2F25" },
    { name: "Fenrisian Grey", hex: "#7491AE" },
    { name: "Fire Dragon Bright", hex: "#E48B5A" },
    { name: "Flash Gitz Yellow", hex: "#FCF351" },
    { name: "Fulgrim Pink", hex: "#E7ACC7" },
    { name: "Gauss Blaster Green", hex: "#8CBDA5" },
    { name: "Genestealer Purple", hex: "#70599E" },
    { name: "Kabalite Green", hex: "#3D8564" },
    { name: "Karak Stone", hex: "#AF9363" },
    { name: "Loren Forest", hex: "#506A32" },
    { name: "Lothern Blue", hex: "#5097C6" },
    { name: "Moot Green", hex: "#5FAB52" },
    { name: "Pink Horror", hex: "#813256" },
    { name: "Russ Grey", hex: "#576E81" },
    { name: "Screaming Skull", hex: "#B8BE9B" },
    { name: "Temple Guard Blue", hex: "#4A9087" },
    { name: "Troll Slayer Orange", hex: "#DF733B" },
    { name: "Ulthuan Grey", hex: "#C7DBD4" },
    { name: "Warpfiend Grey", hex: "#65646C" },
    { name: "White Scar", hex: "#FFFFFF" },
];
