export const colorList = [

    // Base Paints
    { name: "White Scar", hex: "#FFFFFF", type: "Base", brand: "Citadel" },
    { name: "Abaddon Black", hex: "#0f0f0f", type: "Base", brand: "Citadel" },
    { name: "Averlund Sunset", hex: "#FBB81C", type: "Base", brand: "Citadel" },
    { name: "Barak-Nar Burgundy", hex: "#451636", type: "Base", brand: "Citadel" },
    { name: "Bugman's Glow", hex: "#804C43", type: "Base", brand: "Citadel" },
    { name: "Caledor Sky", hex: "#366699", type: "Base", brand: "Citadel" },
    { name: "Caliban Green", hex: "#003D15", type: "Base", brand: "Citadel" },
    { name: "Castellan Green", hex: "#264715", type: "Base", brand: "Citadel" },
    { name: "Catachan Flesh", hex: "#442B25", type: "Base", brand: "Citadel" },
    { name: "Celestra Grey", hex: "#8BA3A3", type: "Base", brand: "Citadel" },
    { name: "Corvus Black", hex: "#171314", type: "Base", brand: "Citadel" },
    { name: "Daemonette Hide", hex: "#655F81", type: "Base", brand: "Citadel" },
    { name: "Death Guard Green", hex: "#6D774D", type: "Base", brand: "Citadel" },
    { name: "Death Korps Drab", hex: "#3D4539", type: "Base", brand: "Citadel" },
    { name: "Deathworld Forest", hex: "#556229", type: "Base", brand: "Citadel" },
    { name: "Dryad Bark", hex: "#2B2A24", type: "Base", brand: "Citadel" },
    { name: "Gal Vorback Red", hex: "#4B213C", type: "Base", brand: "Citadel" },
    { name: "Grey Seer", hex: "#A2A5A7", type: "Base", brand: "Citadel" },
    { name: "Hobgrot Hide", hex: "#A1812A", type: "Base", brand: "Citadel" },
    { name: "Incubi Darkness", hex: "#082E32", type: "Base", brand: "Citadel" },
    { name: "Ionrach Skin", hex: "#97A384", type: "Base", brand: "Citadel" },
    { name: "Jokaero Orange", hex: "#ED3814", type: "Base", brand: "Citadel" },
    { name: "Kantor Blue", hex: "#02134E", type: "Base", brand: "Citadel" },
    { name: "Khorne Red", hex: "#650001", type: "Base", brand: "Citadel" },
    { name: "Lupercal Green", hex: "#002C2B", type: "Base", brand: "Citadel" },
    { name: "Macragge Blue", hex: "#0F3D7C", type: "Base", brand: "Citadel" },
    { name: "Mechanicus Standard Grey", hex: "#39484A", type: "Base", brand: "Citadel" },
    { name: "Mephiston Red", hex: "#960C09", type: "Base", brand: "Citadel" },
    { name: "Morghast Bone", hex: "#C0A973", type: "Base", brand: "Citadel" },
    { name: "Mournfang Brown", hex: "#490F06", type: "Base", brand: "Citadel" },
    { name: "Naggaroth Night", hex: "#3B2B50", type: "Base", brand: "Citadel" },
    { name: "Night Lords Blue", hex: "#002B5C", type: "Base", brand: "Citadel" },
    { name: "Nocturne Green", hex: "#162A29", type: "Base", brand: "Citadel" },
    { name: "Orruk Flesh", hex: "#8CC276", type: "Base", brand: "Citadel" },
    { name: "Phoenician Purple", hex: "#440052", type: "Base", brand: "Citadel" },
    { name: "Rakarth Flesh", hex: "#9C998D", type: "Base", brand: "Citadel" },
    { name: "Ratskin Flesh", hex: "#A86648", type: "Base", brand: "Citadel" },
    { name: "Rhinox Hide", hex: "#462F30", type: "Base", brand: "Citadel" },
    { name: "Screamer Pink", hex: "#7A0E44", type: "Base", brand: "Citadel" },
    { name: "Steel Legion Drab", hex: "#584E2D", type: "Base", brand: "Citadel" },
    { name: "Stegadon Scale Green", hex: "#06455D", type: "Base", brand: "Citadel" },
    { name: "The Fang", hex: "#405B71", type: "Base", brand: "Citadel" },
    { name: "Thondia Brown", hex: "#54302A", type: "Base", brand: "Citadel" },
    { name: "Thousand Sons Blue", hex: "#00506F", type: "Base", brand: "Citadel" },
    { name: "Waaagh! Flesh", hex: "#0B3B36", type: "Base", brand: "Citadel" },
    { name: "Wraithbone", hex: "#DBD1B2", type: "Base", brand: "Citadel" },
    { name: "XV-88", hex: "#6C4811", type: "Base", brand: "Citadel" },
    { name: "Zandri Dust", hex: "#988E56", type: "Base", brand: "Citadel" },

    // Layer Paints
    { name: "Administratum Grey", hex: "#989C94", type: "Layer", brand: "Citadel" },
    { name: "Ahriman Blue", hex: "#00708A", type: "Layer", brand: "Citadel" },
    { name: "Alaitoc Blue", hex: "#2F4F85", type: "Layer", brand: "Citadel" },
    { name: "Altdorf Guard Blue", hex: "#2D4696", type: "Layer", brand: "Citadel" },
    { name: "Baharroth Blue", hex: "#54BDCA", type: "Layer", brand: "Citadel" },
    { name: "Balor Brown", hex: "#875408", type: "Layer", brand: "Citadel" },
    { name: "Baneblade Brown", hex: "#8F7C68", type: "Layer", brand: "Citadel" },
    { name: "Bestigor Flesh", hex: "#D08951", type: "Layer", brand: "Citadel" },
    { name: "Bloodreaver Flesh", hex: "#6A4848", type: "Layer", brand: "Citadel" },
    { name: "Blue Horror", hex: "#9EB5CE", type: "Layer", brand: "Citadel" },
    { name: "Cadian Fleshtone", hex: "#C47652", type: "Layer", brand: "Citadel" },
    { name: "Calgar Blue", hex: "#2A497F", type: "Layer", brand: "Citadel" },
    { name: "Dark Reaper", hex: "#354D4C", type: "Layer", brand: "Citadel" },
    { name: "Dawnstone", hex: "#697068", type: "Layer", brand: "Citadel" },
    { name: "Deathclaw Brown", hex: "#AF634F", type: "Layer", brand: "Citadel" },
    { name: "Dechala Lilac", hex: "#B598C9", type: "Layer", brand: "Citadel" },
    { name: "Deepkin Flesh", hex: "#A9B79F", type: "Layer", brand: "Citadel" },
    { name: "Doombull Brown", hex: "#570003", type: "Layer", brand: "Citadel" },
    { name: "Dorn Yellow", hex: "#FFF55A", type: "Layer", brand: "Citadel" },
    { name: "Elysian Green", hex: "#6B8C37", type: "Layer", brand: "Citadel" },
    { name: "Emperor's Children", hex: "#B74073", type: "Layer", brand: "Citadel" },
    { name: "Eshin Grey", hex: "#484B4E", type: "Layer", brand: "Citadel" },
    { name: "Evil Sunz Scarlet", hex: "#C01411", type: "Layer", brand: "Citadel" },
    { name: "Fenrisian Grey", hex: "#6D94B3", type: "Layer", brand: "Citadel" },
    { name: "Fire Dragon Bright", hex: "#F4874E", type: "Layer", brand: "Citadel" },
    { name: "Flash Gitz Yellow", hex: "#FFF300", type: "Layer", brand: "Citadel" },

    { name: "Flayed One Flesh", hex: "#EEC483", type: "Layer", brand: "Citadel" },

    { name: "Fulgrim Pink", hex: "#F3ABCA", type: "Layer", brand: "Citadel" },
    { name: "Gauss Blaster Green", hex: "#7FC1A5", type: "Layer", brand: "Citadel" },
    { name: "Genestealer Purple", hex: "#7658A5", type: "Layer", brand: "Citadel" },

    { name: "Gorthor Brown", hex: "#5F463F", type: "Layer", brand: "Citadel" },
    { name: "Hoeth Blue", hex: "#4C78AF", type: "Layer", brand: "Citadel" },

    { name: "Kabalite Green", hex: "#008962", type: "Layer", brand: "Citadel" },

    { name: "Kakophoni Purple", hex: "#8869AE", type: "Layer", brand: "Citadel" },

    { name: "Karak Stone", hex: "#B7945C", type: "Layer", brand: "Citadel" },

    { name: "Kislev Flesh", hex: "#D1A570", type: "Layer", brand: "Citadel" },
    { name: "Knight Questor Flesh", hex: "#996563", type: "Layer", brand: "Citadel" },
    { name: "Krieg Khaki", hex: "#BCBB7E", type: "Layer", brand: "Citadel" },

    { name: "Loren Forest", hex: "#486C25", type: "Layer", brand: "Citadel" },
    { name: "Lothern Blue", hex: "#2C9BCC", type: "Layer", brand: "Citadel" },

    { name: "Lugganath Orange", hex: "#F69B82", type: "Layer", brand: "Citadel" },

    { name: "Moot Green", hex: "#3DAF44", type: "Layer", brand: "Citadel" },

    { name: "Nurgling Green", hex: "#7E975E", type: "Layer", brand: "Citadel" },
    { name: "Ogryn Camo", hex: "#96A648", type: "Layer", brand: "Citadel" },
    { name: "Pallid Wych Flesh", hex: "#CACCBB", type: "Layer", brand: "Citadel" },
    { name: "Phalanx Yellow", hex: "#FFE200", type: "Layer", brand: "Citadel" },

    { name: "Pink Horror", hex: "#8E2757", type: "Layer", brand: "Citadel" },
    { name: "Russ Grey", hex: "#507085", type: "Layer", brand: "Citadel" },
    { name: "Screaming Skull", hex: "#B9C099", type: "Layer", brand: "Citadel" },

    { name: "Skarsnik Green", hex: "#588F6B", type: "Layer", brand: "Citadel" },
    { name: "Skavenblight Dinge", hex: "#45413B", type: "Layer", brand: "Citadel" },
    { name: "Skrag Brown", hex: "#8B4806", type: "Layer", brand: "Citadel" },
    { name: "Slaanesh Grey", hex: "#8B8893", type: "Layer", brand: "Citadel" },
    { name: "Sons of Horus Green", hex: "#00545E", type: "Layer", brand: "Citadel" },
    { name: "Sotek Green", hex: "#0B6371", type: "Layer", brand: "Citadel" },
    { name: "Squig Orange", hex: "#A74D42", type: "Layer", brand: "Citadel" },
    { name: "Stormvermin Fur", hex: "#6D655F", type: "Layer", brand: "Citadel" },
    { name: "Straken Green", hex: "#597F1C", type: "Layer", brand: "Citadel" },
    { name: "Sybarite Green", hex: "#17A166", type: "Layer", brand: "Citadel" },

    //Still a lot to add/fix

    { name: "Temple Guard Blue", hex: "#4A9087", type: "Layer", brand: "Citadel" },
    { name: "Troll Slayer Orange", hex: "#DF733B", type: "Layer", brand: "Citadel" },
    { name: "Ulthuan Grey", hex: "#C7DBD4", type: "Layer", brand: "Citadel" },
    { name: "Warpfiend Grey", hex: "#65646C", type: "Layer", brand: "Citadel" },

    // Metallics
    { name: "Grey Knight's Steel", hex: "#a5b4be", type: "Metallic", brand: "Citadel" },
    { name: "Iron Hand's Steel", hex: "#a99d95", type: "Metallic", brand: "Citadel" },
    { name: "Iron Warriors", hex: "#63605d", type: "Metallic", brand: "Citadel" },
    { name: "Leadbelcher", hex: "#8a8a8a", type: "Metallic", brand: "Citadel" },
    { name: "Retributor Armour", hex: "#ebb854", type: "Metallic", brand: "Citadel" },
    { name: "Runelord Brass", hex: "#74624d", type: "Metallic", brand: "Citadel" },
    { name: "Screaming Bell", hex: "#cc7d51", type: "Metallic", brand: "Citadel" },
    { name: "Warplock Bronze", hex: "#aa6243", type: "Metallic", brand: "Citadel" },
    { name: "Balthasar Gold", hex: "#9b684b", type: "Metallic", brand: "Citadel" }
];